import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import '@fontsource/readex-pro'
import { NavBar } from '../components'
import { Card } from '../components/Card/Card'
import { useDataRequest } from '../hooks/useDataRequest'

const Home: NextPage = () => {
	const { data, isLoading } = useDataRequest()

	return (
		<div>
			<Head>
				<title>Asalytics</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/logo.png' />
			</Head>

			<main>
				<NavBar />
				<section>
					<h1>List of Algorand Standard Assets on ASAlytics</h1>
					{isLoading ? (
						<Image src='/infinity.gif' alt='loader' height={65} width={65} />
					) : (
						<>
							<div>
								<Card data={data?.asalist?.result} />
							</div>
						</>
					)}
				</section>
			</main>
		</div>
	)
}

export default Home

//https://analytics-api.herokuapp.com/analytics

// asalist{

//     results{
//       name,
//       logo,
//       available,
//       assetId
//     }
//   }
